[project]
name = "cross-compile"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pyzmq", "protobuf"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["proto", "worker"]

[tool.setuptools.package-dir]
proto = "proto"
worker = "python-worker"

[tool.black]
line-length = 88
