name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:ubuntu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl cmake libprotobuf-dev protobuf-compiler gcc-aarch64-linux-gnu g++-aarch64-linux-gnu python3-pip clang-format
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add aarch64-unknown-linux-gnu
          rustup component add clippy rustfmt
          pip install pytest pre-commit
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Build
        run: make build
      - name: Test
        run: make test
